config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :contacts
  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
  resources :users, param: :name
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  MAX = 100
  scope :index, -> { limit(MAX) }
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :content, length: { in: 1..140 }
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :content, length: { in: 1..140 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :blog, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_secure_password
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  before_save{ email.downcase! }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  protect_from_forgery with: :exception
  include SessionsHelper
  include Banken
  rescue_from Banken::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
    loyalty_name = exception.loyalty.class.to_s.underscore

    flash[:danger] = t "#{loyalty_name}.#{exception.query}", scope: "banken", default: :default
    redirect_to(request.referrer || blogs_path)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_login, only: [:new, :show, :edit, :destroy]
  before_action :authorize_action, only: [:edit, :destroy]

  def new
    if params[:back]
      @blog = current_user.blogs.build(blog_params)
    else
      @blog = current_user.blogs.build
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    @blog.image.retrieve_from_cache! params[:cache][:image] unless params[:cache].nil?
    if @blog.save
      ContactMailer::create_blog_mail(@blog).deliver
      redirect_to blogs_path, flash: { success: t('.success') }
    else
      render :new
    end
  end

  def index
    @blogs = Blog.index
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, flash: { danger: t('.success') }
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @comment = @blog.comments.build
    @comments = @blog.comments
  end

  def edit
  end

  def confirm
    @blog = current_user.blogs.new(blog_params)
    render :new if @blog.invalid?
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, flash: { info: t('.success') }
    else
      render :edit
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def redirect_to_login
    unless logged_in?
      redirect_to new_session_path, flash: { warning: t(:please_login) }
    end
  end

  def authorize_action
    authorize! @blog
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to blog_path(@blog), flash: { success: t('.failed') } }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:blog_id, :content)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer::contact_mail(@contact).deliver
      redirect_to new_contact_path, flash: { info: 'お問い合わせを受け付けました。' }
    else
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blog_url(id: params[:blog_id]),
      flash: { info: "#{favorite.blog.user.name}さんのブログをお気に入りに登録しました" }
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blog_url(id: params[:blog_id]), 
      flash: { warning: "#{favorite.blog.user.name}さんのブログお気に入りを解除しました" }
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.name), flash: { success: t('.success') }
    else
      flash[:danger] = t('.failed')
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:warning] = t('.success')
    redirect_to new_session_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.name), flash: { success: t('.success') }
    else
      render :new
    end
  end

  def show
    @favorite_blogs = @user.favorite_blogs
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.name), flash: { info: t('.success') }
    else
      render :edit
    end
  end

  def index
    @users = User.index
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { danger: t('.success') }
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user = User.find_by(name: params[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit_blog
    if action_name == 'new' or action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit_user
    if action_name == 'new' or action_name == 'confirm'
      users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/blogs/_form.html.slim
.container
  = form_with(model: @blog, local: true, url: choose_new_or_edit_blog) do |form|
    - if @blog.errors.any?
      #error_explanation
        h2
          =t :occurred, count: @blog.errors.count
        ul
          - @blog.errors.full_messages.each do |msg|
            li
              = msg
    .blog_title
      = form.label :title
      = form.text_field :title, class: "form-control", placeholder: "title"
    .blog_content
      = form.label :content
      = form.text_area :content, class: "form-control", placeholder: "content"
    .blog_image
      = form.label :image
      = form.file_field :image, id: :blog_image
      = form.hidden_field :image_cache
    = form.submit t: :submit, class: "btn btn-default"

app/views/blogs/confirm.html.slim
.container
  h1.title
    =t '.title'
  .row
    = form_with(model: @blog, url: blogs_path, local: true) do |form|
      .col-xs-12.col-md-12
        = form.hidden_field :title
        = form.hidden_field :content
        h2
          = t :title
        p
          = @blog.title
        h2
          =t :content
        p
          = @blog.content
        - unless @blog.image_cache.nil?
          p
            = image_tag @blog.image.url
          p
            = hidden_field_tag :"cache[image]", @blog.image.cache_name
      .col-xs-12.col-md-2
        = form.submit t: :submit, class: "btn btn-default"
      .col-xs-12.col-md-2
        = form_with(model: @blog, url: new_blog_path, local: true, method: :get) do |form|
          = form.hidden_field :title
          = form.hidden_field :content
        = form.submit 'Back', name: 'back', class: "btn btn-default"

app/views/blogs/edit.html.slim
h1.title
  =t '.title'
= render 'form'

app/views/blogs/index.html.slim
h1.title
  =t '.title'
.container
  .row
    - @blogs.each do |blog|
      .col-xs-12.col-md-6.blog-panel
        h2
          = blog.title
        p
          = blog.content
        p
          =t :author
          | :
          = blog.user.name
        p
          =t :created_at
          | :
          = blog.created_at
        .blog-link
          = link_to t(:detail), blog_path(blog.id), class: "btn btn-default"
          - if blog.user == current_user
            = link_to t(:edit), edit_blog_path(blog.id), class: "btn btn-info"
            = link_to t(:delete), blog_path(blog.id), method: :delete, data: { confirm: t(:confirm_detele) }, class: "btn btn-danger"
          - else
            = link_to t(:edit), '', class: "btn btn-info", disabled: "disabled"
            = link_to t(:delete), '', class: "btn btn-danger", disabled: "disabled"

app/views/blogs/new.html.slim
h1.title
  = t '.title'
= render 'form'

app/views/blogs/show.html.slim
h1.title
  =t '.title'
.container
  - unless @blog.user == current_user
    - if @favorite.present?
      = link_to favorite_path(blog_id: @blog.id), method: :delete do
        i.fa.fa-star.fa-2x
    - else
      = link_to favorites_path(blog_id: @blog.id), method: :post do
        i.fa.fa-star.faa-flash.animated.fa-2x
  h2
    =t :author
  p
    = @blog.user.name
  h2
    =t :title
  p
    = @blog.title
  h2
    =t :content
  p
    = @blog.content
  p
    = image_tag @blog.image
  h2
    = t :comment
  #comments_area
    = render partial: 'comments/index', locals: { comments: @comments, blog: @blog }
  = render partial: 'comments/form', locals: { comment: @comment, blog: @blog }

app/views/comments/_form.html.slim
= form_with(model: [blog, comment]) do |form|
  - if @comment.errors.any?
    #error_explanation
      h2
        =t :occurred, count: @comment.errors.count
      ul
        - @comment.errors.full_messages.each do |msg|
          li
            = msg
  .comment_content
    / = form.label :content
    = form.text_area :content, class: "form-control", placeholder: "content"
  = form.submit t: :submit, class: "btn btn-default"

app/views/comments/_index.html.slim
ul
  - comments.each do |comment|
    - unless comment.id.nil?
      li
        = comment.content

app/views/comments/index.js.slim
| $("#comments_area").html("#{j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog })}");
| $("textarea").val('');

app/views/contacts/_form.html.slim
.container
  = form_with(model: @contact, local: true, url: contacts_path) do |form|
    - if @contact.errors.any?
      #error_explanation
        h2
          =t 'occurred', count: @contact.errors.count
        ul
          - @contact.errors.full_messages.each do |msg|
            li
              = msg
    .contact_name
      = form.label :name
      = form.text_field :name, class: "form-control", placeholder: "name"
    .contact_email
      = form.label :email
      = form.text_field :email, class: "form-control", placeholder: "email@email.com"
    .contact_content
      = form.label :content
      = form.text_area :content, class: "form-control", placeholder: "content"
    = form.submit t: :submit, class: "btn btn-default"

app/views/contacts/new.html.slim
h1.title
  =t :contact_form
= render 'form'

app/views/static_pages/home.html.slim
.wrapper.clearfix
  section.key_visual
    p
      | Achieve
  .container
    section.preamble
      h1
        | About Achieve
      p
        |  Achieveは、受講生が最低限Railsを動かせるかを測るお試しアプリです。
        br
        |  Achieveを作り終えることで、これからの学習に必要な事前知識を身に着けることができます。 
      p
        |  Acheveを一言で表すと、練習用のブログ作成アプリです。
        br
        |  ブログを投稿する機能をつけることで、Railsの機能の一端を学ぶことができます。 
    section.about
      h2
        | Achieve 合格条件
      p.condition
        input[type="checkbox"]
        |  アソシエーションシリーズ課題で作成したアプリに機能を追加する形で実装すること
        br
        input[type="checkbox"]
        |  メール機能を実装する。
        br
        input[type="checkbox"]
        |  Githubにソースコードを送信し、そのリポジトリのURLを提出すること
        br
        input[type="checkbox"]
        |  Herokuにアップロードしてある状態であること
        br

app/views/users/_form.html.slim
.container
  - unless notice.blank?
    .alert.alert-info.alert-dismissible
      button.close[type="button" data-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"]
          | ×
      = notice
  = form_with(model: @user, local: true, url: choose_new_or_edit_user) do |form|
    - if @user.errors.any?
      #error_explanation
        h2
          =t :occurred, count: @user.errors.count
        ul
          - @user.errors.full_messages.each do |msg|
            li
              = msg
    .user_name
      = form.label :name
      = form.text_field :name, class: "form-control", placeholder: "name"
    .user_email
      = form.label :email
      = form.text_field :email, class: "form-control", placeholder: "email@email.com"
    .user_password
      = form.label :password
      = form.password_field :password, class: "form-control", placeholder: "password"
    .user_password
      = form.label :password_confirmation
      = form.password_field :password_confirmation, class: "form-control", placeholder: "password_confirmation"
    .user_image
      = form.label :image
      = form.file_field :image, id: :user_image
      = form.hidden_field :image_cache
    = form.submit t: :submit, class: "btn btn-default"

app/views/users/edit.html.slim
h1.title
  =t '.title'
= render 'form'

app/views/users/index.html.slim
h1.title
  =t '.title'
.container
  .row
    - @users.each do |user|
      .col-xs-12.col-md-6.user-panel
        p
          = user.name
        p
          = user.email
        .user-link
          = link_to t(:detail), user_path(user.name), class: "btn btn-default"
          - if user == current_user
            = link_to t(:edit), edit_user_path(user.name), class: "btn btn-info"
            = link_to t(:delete), user_path(user.id), method: :delete, data: { confirm: t(:confirm_detele) }, class: "btn btn-danger"
          - else
            = link_to t(:edit), '', class: "btn btn-info", disabled: "disabled"
            = link_to t(:delete), '', class: "btn btn-danger", disabled: "disabled"

app/views/users/new.html.slim
h1.title
  =t '.title'
= render 'form'

app/views/users/show.html.slim
h1.title
  = image_tag @user.image.thumb
  =t '.title', user: @user.name
  = link_to t(:edit), edit_user_path(@user.name), class: "btn btn-link"
.container
  h2
    =t '.favorite_blogs'
  .row
    - @favorite_blogs.each do |blog|
      .col-xs-12.col-md-6.blog-panel
        h2
          = blog.title
        p
          = blog.content
        p
          =t :author
          | :
          = blog.user.name
        p
          =t :created_at
          | :
          = blog.created_at
        = link_to t(:detail), blog_path(blog.id), class: "btn btn-default"