config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :contacts
  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
  resources :users, param: :name
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  MAX = 100
  scope :index, -> { limit(MAX) }
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :content, length: { in: 1..140 }
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :content, length: { in: 1..140 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :blog, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_secure_password
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  before_save{ email.downcase! }
  mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_login, only: [:new, :show, :edit, :destroy]
  before_action :authorize_action, only: [:edit, :destroy]

  def new
    if params[:back]
      @blog = current_user.blogs.build(blog_params)
    else
      @blog = current_user.blogs.build
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    @blog.image.retrieve_from_cache! params[:cache][:image] unless params[:cache].nil?
    if @blog.save
      ContactMailer::create_blog_mail(@blog).deliver
      redirect_to blogs_path, flash: { success: t('.success') }
    else
      render :new
    end
  end

  def index
    @blogs = Blog.index
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, flash: { danger: t('.success') }
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @comment = @blog.comments.build
    @comments = @blog.comments
  end

  def edit
  end

  def confirm
    @blog = current_user.blogs.new(blog_params)
    render :new if @blog.invalid?
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, flash: { info: t('.success') }
    else
      render :edit
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def redirect_to_login
    unless logged_in?
      redirect_to new_session_path, flash: { warning: t(:please_login) }
    end
  end

  def authorize_action
    authorize! @blog
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to blog_path(@blog), flash: { success: t('.failed') } }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:blog_id, :content)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer::contact_mail(@contact).deliver
      redirect_to new_contact_path, flash: { info: 'お問い合わせを受け付けました。' }
    else
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blog_url(id: params[:blog_id]),
      flash: { info: "#{favorite.blog.user.name}さんのブログをお気に入りに登録しました" }
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blog_url(id: params[:blog_id]), 
      flash: { warning: "#{favorite.blog.user.name}さんのブログお気に入りを解除しました" }
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.name), flash: { success: t('.success') }
    else
      flash[:danger] = t('.failed')
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:warning] = t('.success')
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.name), flash: { success: t('.success') }
    else
      render :new
    end
  end

  def show
    @favorite_blogs = @user.favorite_blogs
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.name), flash: { info: t('.success') }
    else
      render :edit
    end
  end

  def index
    @users = User.index
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { danger: t('.success') }
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user = User.find_by(name: params[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit_blog
    if action_name == 'new' or action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit_user
    if action_name == 'new' or action_name == 'confirm'
      users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/layouts/_flash.html.slim
- flash.each do |msg_type, message|
  |  <div class="alert alert-
  = msg_type
  |  alert-dismissible">
  button.close[type="button" data-dismiss="alert" aria-label="Close"]
    span[aria-hidden="true"]
      | ×
  = message
  |  </div>

app/views/layouts/_footer.html.slim
footer.footer
  p
    | Copyright © 伊藤真人 2017年11月期

app/views/layouts/_header.html.slim
header.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header.clearfix
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#gnavi"]
        span.sr-only
          | Bootstrap
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: "navbar-brand"
    #gnavi.collapse.navbar-collapse
      ul.nav.navbar-nav
        - if logged_in?
          li
            = link_to t(:blog_list), blogs_path
          li
            = link_to t(:mypage), user_path(current_user.name)
          li
            = link_to t(:new_post), new_blog_path
          li
            = link_to t(:user_list), users_path
          li
            = link_to t(:log_out), session_path(current_user), method: "delete"
        - else
          li
            = link_to t(:sign_up), new_user_path
          li
            = link_to t(:log_in), new_session_path
        li
          = link_to t(:contact), new_contact_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Achieve
    = csrf_meta_tags
    meta[name="viewport" content="width=device-width"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all"]
    = render 'layouts/header'
  body
    = render 'layouts/flash'
    == yield
    = render 'layouts/footer'